# title: Yourname's Homepage
# page-top-title: Yourname
# top-section-bg-text: Be what you wanna be
# home-subtitle: Yourname&ensp;|&ensp;上杉绘梨衣
# copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'

title: TengYang
page-top-title: TengYang
top-section-bg-text: Be what you wanna be
home-subtitle: TengYang|杨腾
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
